version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    container_name: vuanem-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - /data:/data
